[package]
name = "gpui_medio"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["crates/build_windows", "crates/player_core"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"


[profile.release]
debug = false
strip = "symbols"

[[bin]]
name = "gpui-medio"
path = "src/main.rs"

[dependencies]
gpui-kit.workspace = true
reqwest_client.workspace = true
log.workspace = true
chrono.workspace = true
fern.workspace = true
serde.workspace = true
anyhow.workspace = true
thiserror.workspace = true
reqwest.workspace = true
tokio.workspace = true
futures-util.workspace = true
serde_json.workspace = true
rust-embed.workspace = true
regex.workspace = true
uuid.workspace = true
md5.workspace = true

gstreamer.workspace = true
gstreamer-app.workspace = true
gstreamer-video.workspace = true
build_windows = { path = "crates/build_windows", default-features = false, features = ["runtime"] }
player_core = { path = "crates/player_core" }
image.workspace = true
scraper.workspace = true


[workspace.dependencies]
gpui-kit = "0.6"
reqwest_client = { package = "gpui-pre-reqwest-client", version = "0.3.1" }

log = {version = "0.4.29"}
chrono = {version = "0.4.43", features = ["default"]}
fern = "0.7.1"
serde = "1.0.228"
anyhow = "1.0.100"
thiserror = "2.0.17"
reqwest = { version = "0.13.1", features = ["blocking", "gzip", "json", "multipart", "form", "stream"] }
tokio = {version = "1.49.0", features = ["full"]}
futures-util="0.3.31"
serde_json = "1.0.149"
rust-embed = "8.11.0"
regex = "1.12.3"
uuid = { version = "1.22.0", features = ["v4"] }
md5 = {version = "0.8.0"}
gstreamer = "0.25.1"
gstreamer-app = "0.25.0"
gstreamer-video = "0.25.0"
image = "0.25.8"
scraper= "0.27.0"
